version: "3.8"

services:
  app:
    build: .
    container_name: spring-app
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: "no"
    networks:
      - spring-network

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nyang
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mariadb_data:
